spring:
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: create
  messages:
    encoding: UTF-8

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

api:
  message:
    success: