spring:
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
#        dialect: org.hibernate.dialect.MySQL57Dialect
#        dialect.storage_engine: innodb
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update

#spring.datasource.hikari.jdbc-url=jdbc:h2:mem:testdb;MODE=MYSQL
#spring.datasource.hikari.username=sa
#spring.h2.console.enabled=true
logging:
  level:
    org.hibernate.type.descriptor.sql: trace


springdoc:
  api-docs:
    path: /swagger-ui/api-docs
  swarger-ui:
    path: /swagger-ui/docs