services:

  backend:
    build:
      dockerfile_inline: |
        FROM gradle:8.4-jdk21
        RUN mkdir /app
        WORKDIR /app
        RUN git clone https://github.com/TodayWhatTodo/backend.git /app
        ENTRYPOINT gradle bootRun
    ports:
      - "8080:8080"
    networks:
      - inner-network

  swagger-server:
    build:
      dockerfile_inline: |
        FROM gradle:8.4-jdk21 as builder
        RUN mkdir /app
        WORKDIR /app
        RUN git clone https://github.com/TodayWhatTodo/backend.git /app
        RUN gradle openapi3
        
        FROM swaggerapi/swagger-ui 
        COPY --from=builder /app/build/api-spec/openapi3.yaml /usr/share/nginx/html/openapi.yaml

    ports:
      - "8000:8080"
    environment:
      - URL=./openapi.yaml
    networks:
      - inner-network

networks:
  inner-network: